name: Build Sing-box SRS Rule

on:
  push:
    branches:
      - master # 或者你的主要分支名
    paths:
      - 'config/singbox/rules/cn.json'
      - 'config/singbox/rules/download.json'
      - 'config/singbox/rules/av.json'
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Sing-box
        run: |
          go install github.com/sagernet/sing-box/cmd/sing-box@latest
          # 验证安装
          ~/go/bin/sing-box version

      - name: Compile SRS files
        run: |
          # 编译规则文件
          ~/go/bin/sing-box rule-set compile --output config/singbox/rules/cn.srs config/singbox/rules/cn.json
          ~/go/bin/sing-box rule-set compile --output config/singbox/rules/download.srs config/singbox/rules/download.json
          ~/go/bin/sing-box rule-set compile --output config/singbox/rules/av.srs config/singbox/rules/av.json

      - name: Commit and push SRS files
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 添加所有变动的 srs 文件
          git add config/singbox/rules/cn.srs
          git add config/singbox/rules/download.srs
          git add config/singbox/rules/av.srs
          
          # 检查是否有文件变动
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated: Build cn.srs, download.srs and av.srs"
            git push
          fi
